# docker-compose.yml

version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5001"  # Mapeia a porta 5001 do contêiner para a porta 5001 no host
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: icct
